[project]
name = "async-log-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "colorama>=0.4.6",
    "tqdm>=4.67.3",
]
